name: Testing Dastardly Integration with GitHub

on: [push]

jobs:
  dastardly_job:
    name: Run Dastardly Integration   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dastardly Action Step
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'

      # You can replace this next step with any JUnit XML parser of your choosing
      - name: Publish Test Report
        if: always()                                    # Forces this step to always run
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'dastardly-report.xml'          # Adjust the path if necessary
          require_tests: true
      # Add a new step to upload the XML report as an artifact
      - name: Upload Dastardly Report
        if: always()                                    # Forces this step to always run
        uses: actions/upload-artifact@v2
        with:
          name: dastardly-report
          path: dastardly-report.xml   
